[[ISSUERS]]
address = "rh5eaqZhAwHu2Wdzhm22yFsde9NMvGCGXG"
name = "XRPTEST1"

[[TOKENS]]
issuer = "rh5eaqZhAwHu2Wdzhm22yFsde9NMvGCGXG"
currency = "reset"
name = "XRPTEST1"
desc = "Test token for XRPL launch process verification."
icon = "https://e92stealth.github.io/icon.png"

[[TOKENS.URLS]]
url = "https://e92stealth.github.io"
type = "website"

[[TOKENS.URLS]]
url = https://www.tiktok.com/@digitalreset2026
type = "social"
